version: '3.8'

services:
  # Serviço da API
  api:
    build: .
    container_name: gestao_escolar_api
    ports:
      - "8000:8080" # Mapeia a porta 8000 do host para a 8080 do contêiner
    environment:
      # Passa a URL do banco de dados para a aplicação.
      # O hostname 'db' é o nome do serviço do banco de dados abaixo.
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/escola_db
    depends_on:
      - db # Garante que o banco de dados inicie antes da API
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: gestao_escolar_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=escola_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: